# OpenAPI Specification for JustWorks Authentication API
openapi: 3.0.3
info:
  title: JustWorks Authentication API
  version: '1.0.0'
  description: |
    Machine-readable API contract for all authentication endpoints (JWT, OAuth2, SSO, Google, Apple, Admin roles, etc).
    Compatible with Swagger UI, Postman, and code generators.
servers:
  - url: https://api.justworks.com/v1
paths:
  /auth/login:
    post:
      summary: User login with email/password or OAuth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Authenticated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
  /auth/oauth/google:
    post:
      summary: Google OAuth sign-in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OAuthRequest'
      responses:
        '200':
          description: Authenticated via Google
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid OAuth token
  /auth/oauth/apple:
    post:
      summary: Apple OAuth sign-in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OAuthRequest'
      responses:
        '200':
          description: Authenticated via Apple
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid OAuth token
  /auth/profile:
    get:
      summary: Fetch user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
        '401':
          description: Unauthorized
  /auth/profile/link:
    post:
      summary: Link external OAuth provider to account
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LinkRequest'
      responses:
        '200':
          description: Account linked
        '400':
          description: Linking failed
  /auth/profile/unlink:
    post:
      summary: Unlink external OAuth provider
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UnlinkRequest'
      responses:
        '200':
          description: Account unlinked
        '400':
          description: Unlinking failed
  /auth/admin/roles:
    post:
      summary: Manage user roles (admin only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleRequest'
      responses:
        '200':
          description: Roles updated
        '403':
          description: Forbidden
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    OAuthRequest:
      type: object
      properties:
        provider:
          type: string
        token:
          type: string
    AuthResponse:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        expires_in:
          type: integer
        user:
          $ref: '#/components/schemas/ProfileResponse'
    ProfileResponse:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        name:
          type: string
        roles:
          type: array
          items:
            type: string
        linked_providers:
          type: array
          items:
            type: string
    LinkRequest:
      type: object
      properties:
        provider:
          type: string
        token:
          type: string
    UnlinkRequest:
      type: object
      properties:
        provider:
          type: string
    RoleRequest:
      type: object
      properties:
        user_id:
          type: string
        roles:
          type: array
          items:
            type: string
